-------------------------------------------------------
-- /* PROCESAMIENTO CAPAS ESPACIALES IDE SUBPESCA */ --
-------------------------------------------------------

-------------------------------
-- /* 1. Areas de Colecta */ --
-------------------------------
DROP TABLE IF EXISTS capas_estaticas.areas_colecta;

CREATE TABLE capas_estaticas.areas_colecta AS
(SELECT "REP_SUBPESCA2.ADM_UOT.ACUI_SSPA_PO_AREACOLECTA.OBJECTID" objectid,
 		 geom,
		"REP_SUBPESCA2.ADM_UOT.ACUI_SSPA_T_AREACOLECTA.NOMBRE" nom_area,
		"REP_SUBPESCA2.ADM_UOT.ACUI_SSPA_T_AREACOLECTA.C_COMUNA" comuna,
		"REP_SUBPESCA2.ADM_UOT.ACUI_SSPA_T_AREACOLECTA.SECTOR" ubicaion,
		"REP_SUBPESCA2.ADM_UOT.ACUI_SSPA_T_AREACOLECTA.SUPERFICIE" superficie,
		"REP_SUBPESCA2.ADM_UOT.ACUI_SSPA_T_AREACOLECTA.C_ESTADOAC" estado,
		"REP_SUBPESCA2.ADM_UOT.ACUI_SSPA_T_AREACOLECTA.N_DECSSFFAA" n_decreto,
		"REP_SUBPESCA2.ADM_UOT.ACUI_SSPA_T_AREACOLECTA.F_DECSSFFAA" f_decreto
FROM entradas.areas_colecta);

--------------------
-- /* 2. ECMPO */ --
--------------------

DROP TABLE IF EXISTS capas_estaticas.ecmpo;

CREATE TABLE capas_estaticas.ecmpo AS
(SELECT "REP_SUBPESCA2.ADM_UAI.AIND_SSP_T_ECMPO.NOMBRE" nombre,
		geom,
		"REP_SUBPESCA2.ADM_UAI.AIND_SSP_T_ECMPO.SOLICITANTE" solicitante,
		"REP_SUBPESCA2.ADM_UAI.AIND_SSP_T_ECMPO.NATURALEZASECTOR" naturaleza,
		"REP_SUBPESCA2.ADM_UAI.AIND_SSP_T_ECMPO.C_ESTADOECMPO" estado,
		"REP_SUBPESCA2.ADM_UAI.AIND_SSP_T_ECMPO.N_INGRESOCI" n_ingreso,
		"REP_SUBPESCA2.ADM_UAI.AIND_SSP_T_ECMPO.F_INGRESOCI" f_ingreso,
		"REP_SUBPESCA2.ADM_UAI.AIND_SSP_T_ECMPO.F_APRUEBAPLANADM" f_aprob,
		"REP_SUBPESCA2.ADM_UAI.AIND_SSP_T_ECMPO.COMUNA" comuna,
		"REP_SUBPESCA2.ADM_UAI.AIND_SSP_T_ECMPO.ES_DECRETADO" decretado,
		"REP_SUBPESCA2.ADM_UAI.AIND_SSP_PO_ECMPO.OBJECTID" objectid,
		"REP_SUBPESCA2.ADM_UAI.AIND_SSP_T_ECMPO.SUPERFICIE" superficie,
		"REP_SUBPESCA2.ADM_UAI.AIND_SSP_T_ECMPO.ES_ACTIVO" activo,
		"REP_SUBPESCA2.ADM_UAI.AIND_SSP_T_ECMPO.N_DECRETOMINDEF" n_decreto,
		"REP_SUBPESCA2.ADM_UAI.AIND_SSP_T_ECMPO.F_DECRETOMINDEF" f_decreto,
		"REP_SUBPESCA2.ADM_UAI.AIND_SSP_T_ECMPO.N_RSSP" resolucion,
		"REP_SUBPESCA2.ADM_UAI.AIND_SSP_T_ECMPO.F_RSSP" f_resolucion
FROM entradas.ecmpo);


--------------------
-- /* 3. AMERB */ --
--------------------
DROP TABLE IF EXISTS capas_estaticas.amerb;

CREATE TABLE capas_estaticas.amerb AS 
(SELECT "REP_SUBPESCA2.ADM_URB.RRBB_SSP_T_AMERB.F_ING_SSP" fecha_ing,
		"REP_SUBPESCA2.ADM_URB.RRBB_SSP_T_AMERB.NOMBRE" nombre,
		geom,
		"REP_SUBPESCA2.ADM_URB.RRBB_SSP_T_AMERB.C_COMUNA" comuna,
		"REP_SUBPESCA2.ADM_URB.RRBB_SSP_T_AMERB.C_ESTADOAMERB" estado,
		"REP_SUBPESCA2.ADM_URB.RRBB_SSP_T_AMERB.C_CATEGORIA" categoria,
		"REP_SUBPESCA2.ADM_URB.RRBB_SSP_T_AMERB.DETALLEESTADO" d_estado,
		"REP_SUBPESCA2.ADM_URB.RRBB_SSP_T_AMERB.SUPERFICIE" superficie,
		"REP_SUBPESCA2.ADM_URB.RRBB_SSP_T_AMERB.N_MINECON" n_decreto_e,
		"REP_SUBPESCA2.ADM_URB.RRBB_SSP_T_AMERB.F_MINECON" f_decreto_e,
		"REP_SUBPESCA2.ADM_URB.RRBB_SSP_T_AMERB.N_DECRETOSSFFAA" n_decreto_d,
		"REP_SUBPESCA2.ADM_URB.RRBB_SSP_T_AMERB.F_DECRETOSSFFAA" f_decreto_d,
		"REP_SUBPESCA2.ADM_URB.RRBB_SSP_T_AMERB.N_DECRETORENOV" n_decreto_r,
		"REP_SUBPESCA2.ADM_URB.RRBB_SSP_T_AMERB.F_DECRETORENOV" f_decreto_r,
		"REP_SUBPESCA2.ADM_URB.RRBB_SSP_T_AMERB.VIGENCIA" vigencia,
		"REP_SUBPESCA2.ADM_URB.RRBB_SSP_T_AMERB.N_RPA" n_rpa,
		"REP_SUBPESCA2.ADM_URB.RRBB_SSP_T_AMERB.F_RPA" f_rpa,
		"REP_SUBPESCA2.ADM_URB.RRBB_SSP_T_AMERB.ORGANIZACION" organizacion,
		"REP_SUBPESCA2.ADM_URB.RRBB_SSP_T_AMERB.ESPECIES" especies,
		"REP_SUBPESCA2.ADM_URB.RRBB_SSP_PO_AMERB.OBJECTID" objectid
FROM entradas.amerb);

-----------------------------------
-- /* 4. Acuicultura en AMERB */ --
-----------------------------------

DROP TABLE IF EXISTS capas_estaticas.acuiamerb;

CREATE TABLE capas_estaticas.acuiamerb AS
(SELECT "REP_SUBPESCA2.ADM_UOT.ACUI_SSP_T_ACUICULTURAAMERB.TITULAR" titular,
		geom,
		"REP_SUBPESCA2.ADM_UOT.ACUI_SSP_T_ACUICULTURAAMERB.C_TIPOACUIAME" tipo_actividad,
		"REP_SUBPESCA2.ADM_UOT.ACUI_SSP_T_ACUICULTURAAMERB.N_PERT" n_pert,
		"REP_SUBPESCA2.ADM_UOT.ACUI_SSP_T_ACUICULTURAAMERB.N_INGRESOCI" n_ingreso,
		"REP_SUBPESCA2.ADM_UOT.ACUI_SSP_T_ACUICULTURAAMERB.F_INGRESOCI" fecha_ing,
		"REP_SUBPESCA2.ADM_UOT.ACUI_SSP_T_ACUICULTURAAMERB.CULTIVO" grupo_esp,
		"REP_SUBPESCA2.ADM_UOT.ACUI_SSP_T_ACUICULTURAAMERB.ESPECIE" especies,
		"REP_SUBPESCA2.ADM_UOT.ACUI_SSP_T_ACUICULTURAAMERB.SUPERFICIE" superficie,
		"REP_SUBPESCA2.ADM_UOT.ACUI_SSP_T_ACUICULTURAAMERB.UBICACIONGEOG" ubicacion,
		"REP_SUBPESCA2.ADM_UOT.ACUI_SSP_T_ACUICULTURAAMERB.Comuna" comuna,
		"REP_SUBPESCA2.ADM_UOT.ACUI_SSP_T_ACUICULTURAAMERB.TIPOCONCESION" t_concesion,
		"REP_SUBPESCA2.ADM_UOT.ACUI_SSP_T_ACUICULTURAAMERB.ESTADO" est_tram,
		"REP_SUBPESCA2.ADM_UOT.ACUI_SSP_PO_ACUICULTURA.OBJECTID" objectid,
		"REP_SUBPESCA2.ADM_UOT.ACUI_SSP_T_ACUICULTURAAMERB.TipoAmerb" tipo
FROM entradas.acuiamerb);
